# Generated by Django 2.2 on 2019-05-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Email',
            field=models.EmailField(max_length=200),
        ),
    ]
