# Generated by Django 2.2.2 on 2019-08-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='appointment_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
