# Generated by Django 2.2.2 on 2019-08-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190831_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
