# Generated by Django 2.2.2 on 2019-08-31 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190831_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 14, 19, 1, 593659, tzinfo=utc)),
        ),
    ]
