# Generated by Django 2.2.2 on 2019-08-31 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20190901_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuser',
            name='name',
            field=models.CharField(default='qweqwe', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2019, 8, 31, 19, 56, 5, 236880, tzinfo=utc), max_length=255),
        ),
    ]
