# Generated by Django 2.2.2 on 2019-08-31 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20190901_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuser',
            name='context',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactuser',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactuser',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactuser',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactuser',
            name='surname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2019, 8, 31, 20, 4, 2, 650026, tzinfo=utc), max_length=255),
        ),
    ]
