# Generated by Django 2.2.2 on 2019-09-01 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_auto_20190901_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2019, 9, 1, 16, 11, 25, 256444, tzinfo=utc), max_length=255),
        ),
    ]
