# Generated by Django 2.2.2 on 2019-09-02 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0064_auto_20190901_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='Category',
            field=models.CharField(choices=[('Music', 'Music'), ('Rock', 'Rock'), ('Jazz', 'Jazz')], default='green', max_length=6),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2019, 9, 2, 9, 20, 48, 14366, tzinfo=utc), max_length=255),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
