# Generated by Django 2.2.2 on 2019-09-02 11:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0068_auto_20190902_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(upload_to='media/event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2019, 9, 2, 11, 27, 56, 203559, tzinfo=utc), max_length=255),
        ),
    ]
