# Generated by Django 2.2.2 on 2019-09-02 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0069_auto_20190902_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2019, 9, 2, 12, 23, 37, 819855, tzinfo=utc), max_length=255),
        ),
    ]
