# Generated by Django 2.2.2 on 2019-09-02 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0071_auto_20190902_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2019, 9, 2, 12, 34, 56, 121774, tzinfo=utc), max_length=255),
        ),
    ]
