# Generated by Django 2.2.2 on 2019-09-03 08:51

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0072_auto_20190902_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Visual Arts', 'Visual Arts'), ('Film', 'Film'), ('Performing Arts', 'Performing Arts'), ('Lectures', 'Lectures'), ('Books', 'Books'), ('Food&Dring', 'Food&Dring'), ('Nightlife', 'Nightlife')], default='green', max_length=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2019, 9, 3, 8, 51, 27, 235360, tzinfo=utc), max_length=255),
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(null=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
