# Generated by Django 2.2.2 on 2019-09-03 09:49

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0073_auto_20190903_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2019, 9, 3, 9, 49, 47, 198428, tzinfo=utc), max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
