# Generated by Django 2.2.2 on 2019-09-03 10:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0075_auto_20190903_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2019, 9, 3, 10, 43, 22, 799961, tzinfo=utc), max_length=255),
        ),
    ]
